#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v21
# autospec commit: 5424026
#
# Source0 file verified with key 0x18DCA123F949BD3B (pascal@obry.net)
#
Name     : darktable
Version  : 5.0.0
Release  : 96
URL      : https://github.com/darktable-org/darktable/releases/download/release-5.0.0/darktable-5.0.0.tar.xz
Source0  : https://github.com/darktable-org/darktable/releases/download/release-5.0.0/darktable-5.0.0.tar.xz
Source1  : https://github.com/darktable-org/rawspeed/archive/ce7278d67179c0d3215f5695e422fea0ec342c2d/rawspeed-ce7278d67179c0d3215f5695e422fea0ec342c2d.tar.gz
Source2  : https://github.com/darktable-org/darktable/releases/download/release-5.0.0/darktable-5.0.0.tar.xz.asc
Source3  : 18DCA123F949BD3B.pkey
Summary  : A virtual Lighttable and Darkroom
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause-FreeBSD BSD-3-Clause CDDL-1.0 GPL-3.0 GPL-3.0+ LGPL-2.1 MIT WTFPL
Requires: darktable-bin = %{version}-%{release}
Requires: darktable-data = %{version}-%{release}
Requires: darktable-lib = %{version}-%{release}
Requires: darktable-license = %{version}-%{release}
Requires: darktable-locales = %{version}-%{release}
Requires: darktable-man = %{version}-%{release}
Requires: iso-codes
BuildRequires : Imath-dev
BuildRequires : SDL2-dev
BuildRequires : buildreq-cmake
BuildRequires : cmake
BuildRequires : cmocka-dev
BuildRequires : colord-dev
BuildRequires : cups-dev
BuildRequires : curl-dev
BuildRequires : desktop-file-utils
BuildRequires : doxygen
BuildRequires : exiv2-dev
BuildRequires : expat-dev
BuildRequires : extra-cmake-modules
BuildRequires : gettext-dev
BuildRequires : glib-dev
BuildRequires : glibc-dev
BuildRequires : gnupg
BuildRequires : gtk3-dev
BuildRequires : icu4c-dev
BuildRequires : intltool
BuildRequires : json-glib-dev
BuildRequires : lcms2-dev
BuildRequires : lensfun-dev
BuildRequires : libICE-dev
BuildRequires : libSM-dev
BuildRequires : libX11-dev
BuildRequires : libXScrnSaver-dev
BuildRequires : libXau-dev
BuildRequires : libXcomposite-dev
BuildRequires : libXcursor-dev
BuildRequires : libXdamage-dev
BuildRequires : libXdmcp-dev
BuildRequires : libXext-dev
BuildRequires : libXfixes-dev
BuildRequires : libXft-dev
BuildRequires : libXi-dev
BuildRequires : libXinerama-dev
BuildRequires : libXmu-dev
BuildRequires : libXpm-dev
BuildRequires : libXrandr-dev
BuildRequires : libXrender-dev
BuildRequires : libXres-dev
BuildRequires : libXt-dev
BuildRequires : libXtst-dev
BuildRequires : libXv-dev
BuildRequires : libXxf86vm-dev
BuildRequires : libavif-dev
BuildRequires : libffi-dev
BuildRequires : libgphoto2-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libpng-dev
BuildRequires : librsvg-dev
BuildRequires : libsoup-dev
BuildRequires : libwebp-dev
BuildRequires : libxml2-dev
BuildRequires : libxslt-dev
BuildRequires : llvm
BuildRequires : llvm-dev
BuildRequires : lua-dev
BuildRequires : ncurses-data
BuildRequires : ocl-icd-dev
BuildRequires : opencl-headers-dev
BuildRequires : openjpeg
BuildRequires : openjpeg-dev
BuildRequires : openjpeg-staticdev
BuildRequires : osm-gps-map-dev
BuildRequires : perl(XML::Parser)
BuildRequires : pkg-config
BuildRequires : pkgconfig(MagickWand)
BuildRequires : pkgconfig(OpenEXR)
BuildRequires : pkgconfig(colord)
BuildRequires : pkgconfig(colord-gtk)
BuildRequires : pkgconfig(exiv2)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(iso-codes)
BuildRequires : pkgconfig(json-glib-1.0)
BuildRequires : pkgconfig(lcms2)
BuildRequires : pkgconfig(lensfun)
BuildRequires : pkgconfig(libgphoto2)
BuildRequires : pkgconfig(libgphoto2_port)
BuildRequires : pkgconfig(libraw)
BuildRequires : pkgconfig(libraw_r)
BuildRequires : pkgconfig(libsecret-1)
BuildRequires : pkgconfig(libwebp)
BuildRequires : pkgconfig(portmidi)
BuildRequires : po4a
BuildRequires : portmidi-dev
BuildRequires : pugixml-dev
BuildRequires : python3-dev
BuildRequires : sqlite-autoconf-dev
BuildRequires : tiff-dev
BuildRequires : zlib-dev
BuildRequires : zstd-dev
Patch1: default-fpmath.patch

%description
darktable is a virtual lighttable and darkroom for photographers: it manages
your digital negatives in a database and lets you view them through a zoomable
lighttable. it also enables you to develop raw images and enhance them.

%package bin
Summary: bin components for the darktable package.
Group: Binaries
Requires: darktable-data = %{version}-%{release}
Requires: darktable-license = %{version}-%{release}

%description bin
bin components for the darktable package.


%package data
Summary: data components for the darktable package.
Group: Data

%description data
data components for the darktable package.


%package doc
Summary: doc components for the darktable package.
Group: Documentation
Requires: darktable-man = %{version}-%{release}

%description doc
doc components for the darktable package.


%package lib
Summary: lib components for the darktable package.
Group: Libraries
Requires: darktable-data = %{version}-%{release}
Requires: darktable-license = %{version}-%{release}

%description lib
lib components for the darktable package.


%package license
Summary: license components for the darktable package.
Group: Default

%description license
license components for the darktable package.


%package locales
Summary: locales components for the darktable package.
Group: Default

%description locales
locales components for the darktable package.


%package man
Summary: man components for the darktable package.
Group: Default

%description man
man components for the darktable package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE3}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE2} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) 18DCA123F949BD3B' gpg.status
%setup -q -n darktable-5.0.0
cd %{_builddir}
tar xf %{_sourcedir}/rawspeed-ce7278d67179c0d3215f5695e422fea0ec342c2d.tar.gz
cd %{_builddir}/darktable-5.0.0
mkdir -p src/external/rawspeed
cp -r %{_builddir}/rawspeed-ce7278d67179c0d3215f5695e422fea0ec342c2d/* %{_builddir}/darktable-5.0.0/src/external/rawspeed
%patch -P 1 -p1
pushd ..
cp -a darktable-5.0.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1735598815
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -falign-functions=32 -fno-lto -fno-semantic-interposition "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -falign-functions=32 -fno-lto -fno-semantic-interposition "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -falign-functions=32 -fno-lto -fno-semantic-interposition "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -falign-functions=32 -fno-lto -fno-semantic-interposition "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo \
-DDONT_USE_INTERNAL_LUA=Off \
-DBINARY_PACKAGE_BUILD=ON \
-DRAWSPEED_ENABLE_LTO=ON \
-DDONT_USE_INTERNAL_LIBRAW=ON  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -falign-functions=32 -fno-lto -fno-semantic-interposition "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -falign-functions=32 -fno-lto -fno-semantic-interposition "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -falign-functions=32 -fno-lto -fno-semantic-interposition "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -falign-functions=32 -fno-lto -fno-semantic-interposition "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo \
-DDONT_USE_INTERNAL_LUA=Off \
-DBINARY_PACKAGE_BUILD=ON \
-DRAWSPEED_ENABLE_LTO=ON \
-DDONT_USE_INTERNAL_LIBRAW=ON  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -falign-functions=32 -fno-lto -fno-semantic-interposition "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -falign-functions=32 -fno-lto -fno-semantic-interposition "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -falign-functions=32 -fno-lto -fno-semantic-interposition "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -falign-functions=32 -fno-lto -fno-semantic-interposition "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1735598815
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/darktable
cp %{_builddir}/darktable-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/darktable/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/darktable-%{version}/data/pswp/LICENSE %{buildroot}/usr/share/package-licenses/darktable/d9f41c058914394e203adb253057643e047576a3 || :
cp %{_builddir}/darktable-%{version}/src/external/LibRaw-cmake/LICENSE %{buildroot}/usr/share/package-licenses/darktable/ff3ed70db4739b3c6747c7f624fe2bad70802987 || :
cp %{_builddir}/darktable-%{version}/src/external/LibRaw/LICENSE.CDDL %{buildroot}/usr/share/package-licenses/darktable/c24b9c7ef03687bf0141f85a1b7ed81459944c3c || :
cp %{_builddir}/darktable-%{version}/src/external/LibRaw/LICENSE.LGPL %{buildroot}/usr/share/package-licenses/darktable/39a21f33cadea18adcc23bf808d7d5ea6419c8b1 || :
cp %{_builddir}/darktable-%{version}/src/external/LuaAutoC/LICENSE.md %{buildroot}/usr/share/package-licenses/darktable/6baddc7988322d021a187ff7d1d0fb9e2a784e20 || :
cp %{_builddir}/darktable-%{version}/src/external/OpenCL/LICENSE %{buildroot}/usr/share/package-licenses/darktable/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/darktable-%{version}/src/external/libxcf/LICENSE %{buildroot}/usr/share/package-licenses/darktable/fc356b2c50a063b663cc14dde29bc0ab9e7bec51 || :
cp %{_builddir}/darktable-%{version}/src/external/rawspeed/LICENSE %{buildroot}/usr/share/package-licenses/darktable/3704f4680301a60004b20f94e0b5b8c7ff1484a9 || :
cp %{_builddir}/darktable-%{version}/src/external/whereami/LICENSE.MIT %{buildroot}/usr/share/package-licenses/darktable/c996ffd4c579d586b7d86e158af6042018c3c422 || :
cp %{_builddir}/darktable-%{version}/src/external/whereami/LICENSE.WTFPLv2 %{buildroot}/usr/share/package-licenses/darktable/75e5bae837deb898dae4cb65c4890b1ab825c6b6 || :
cp %{_builddir}/rawspeed-ce7278d67179c0d3215f5695e422fea0ec342c2d/LICENSE %{buildroot}/usr/share/package-licenses/darktable/3704f4680301a60004b20f94e0b5b8c7ff1484a9 || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
%find_lang darktable
## install_append content

ln -s darktable/libdarktable.so %{buildroot}/usr/lib64/libdarktable.so
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/darktable
/V3/usr/bin/darktable-chart
/V3/usr/bin/darktable-cli
/V3/usr/bin/darktable-cltest
/V3/usr/bin/darktable-cmstest
/V3/usr/bin/darktable-generate-cache
/V3/usr/bin/darktable-rs-identify
/usr/bin/darktable
/usr/bin/darktable-chart
/usr/bin/darktable-cli
/usr/bin/darktable-cltest
/usr/bin/darktable-cmstest
/usr/bin/darktable-generate-cache
/usr/bin/darktable-rs-identify

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.darktable.darktable.desktop
/usr/share/darktable/darktable.bash
/usr/share/darktable/darktablerc
/usr/share/darktable/gdb_commands
/usr/share/darktable/kernels/atrous.cl
/usr/share/darktable/kernels/basecurve.cl
/usr/share/darktable/kernels/basic.cl
/usr/share/darktable/kernels/basicadj.cl
/usr/share/darktable/kernels/bilateral.cl
/usr/share/darktable/kernels/blendop.cl
/usr/share/darktable/kernels/bloom.cl
/usr/share/darktable/kernels/blurs.cl
/usr/share/darktable/kernels/bspline.cl
/usr/share/darktable/kernels/channelmixer.cl
/usr/share/darktable/kernels/color_conversion.h
/usr/share/darktable/kernels/colorequal.cl
/usr/share/darktable/kernels/colorreconstruction.cl
/usr/share/darktable/kernels/colorspace.h
/usr/share/darktable/kernels/colorspaces.cl
/usr/share/darktable/kernels/common.h
/usr/share/darktable/kernels/demosaic_markesteijn.cl
/usr/share/darktable/kernels/demosaic_other.cl
/usr/share/darktable/kernels/demosaic_ppg.cl
/usr/share/darktable/kernels/demosaic_rcd.cl
/usr/share/darktable/kernels/demosaic_vng.cl
/usr/share/darktable/kernels/denoiseprofile.cl
/usr/share/darktable/kernels/diffuse.cl
/usr/share/darktable/kernels/dwt.cl
/usr/share/darktable/kernels/extended.cl
/usr/share/darktable/kernels/filmic.cl
/usr/share/darktable/kernels/gaussian.cl
/usr/share/darktable/kernels/guided_filter.cl
/usr/share/darktable/kernels/hazeremoval.cl
/usr/share/darktable/kernels/highpass.cl
/usr/share/darktable/kernels/liquify.cl
/usr/share/darktable/kernels/locallaplacian.cl
/usr/share/darktable/kernels/lut3d.cl
/usr/share/darktable/kernels/negadoctor.cl
/usr/share/darktable/kernels/nlmeans.cl
/usr/share/darktable/kernels/noise_generator.h
/usr/share/darktable/kernels/programs.conf
/usr/share/darktable/kernels/retouch.cl
/usr/share/darktable/kernels/rgb_norms.h
/usr/share/darktable/kernels/rgbcurve.cl
/usr/share/darktable/kernels/rgblevels.cl
/usr/share/darktable/kernels/sharpen.cl
/usr/share/darktable/kernels/sigmoid.cl
/usr/share/darktable/kernels/soften.cl
/usr/share/darktable/latex/photobook.cls
/usr/share/darktable/lua/darktable/debug.lua
/usr/share/darktable/luarc
/usr/share/darktable/noiseprofiles.json
/usr/share/darktable/pixmaps/clock.svg
/usr/share/darktable/pixmaps/darktable.svg
/usr/share/darktable/pixmaps/dt_logo_128x128.png
/usr/share/darktable/pixmaps/dt_text.svg
/usr/share/darktable/pixmaps/idbutton-1.png
/usr/share/darktable/pixmaps/idbutton-1.svg
/usr/share/darktable/pixmaps/idbutton-2.png
/usr/share/darktable/pixmaps/idbutton-2.svg
/usr/share/darktable/pixmaps/idbutton-3.png
/usr/share/darktable/pixmaps/idbutton-3.svg
/usr/share/darktable/pixmaps/idbutton.png
/usr/share/darktable/pixmaps/idbutton.svg
/usr/share/darktable/pixmaps/macos_install_background.svg
/usr/share/darktable/pixmaps/plugins/darkroom/ashift.png
/usr/share/darktable/pixmaps/plugins/darkroom/ashift.svg
/usr/share/darktable/pixmaps/plugins/darkroom/atrous.png
/usr/share/darktable/pixmaps/plugins/darkroom/atrous.svg
/usr/share/darktable/pixmaps/plugins/darkroom/basecurve.png
/usr/share/darktable/pixmaps/plugins/darkroom/basecurve.svg
/usr/share/darktable/pixmaps/plugins/darkroom/bilateral.png
/usr/share/darktable/pixmaps/plugins/darkroom/bilateral.svg
/usr/share/darktable/pixmaps/plugins/darkroom/bloom.png
/usr/share/darktable/pixmaps/plugins/darkroom/bloom.svg
/usr/share/darktable/pixmaps/plugins/darkroom/borders.png
/usr/share/darktable/pixmaps/plugins/darkroom/borders.svg
/usr/share/darktable/pixmaps/plugins/darkroom/cacorrect.png
/usr/share/darktable/pixmaps/plugins/darkroom/cacorrect.svg
/usr/share/darktable/pixmaps/plugins/darkroom/channelmixer.png
/usr/share/darktable/pixmaps/plugins/darkroom/channelmixer.svg
/usr/share/darktable/pixmaps/plugins/darkroom/clahe.png
/usr/share/darktable/pixmaps/plugins/darkroom/clahe.svg
/usr/share/darktable/pixmaps/plugins/darkroom/clipping.png
/usr/share/darktable/pixmaps/plugins/darkroom/clipping.svg
/usr/share/darktable/pixmaps/plugins/darkroom/colisa.png
/usr/share/darktable/pixmaps/plugins/darkroom/colisa.svg
/usr/share/darktable/pixmaps/plugins/darkroom/colorcorrection.png
/usr/share/darktable/pixmaps/plugins/darkroom/colorcorrection.svg
/usr/share/darktable/pixmaps/plugins/darkroom/colorin.png
/usr/share/darktable/pixmaps/plugins/darkroom/colorin.svg
/usr/share/darktable/pixmaps/plugins/darkroom/colormapping.png
/usr/share/darktable/pixmaps/plugins/darkroom/colormapping.svg
/usr/share/darktable/pixmaps/plugins/darkroom/colorout.png
/usr/share/darktable/pixmaps/plugins/darkroom/colorout.svg
/usr/share/darktable/pixmaps/plugins/darkroom/colorreconstruct.png
/usr/share/darktable/pixmaps/plugins/darkroom/colorreconstruct.svg
/usr/share/darktable/pixmaps/plugins/darkroom/colortransfer.png
/usr/share/darktable/pixmaps/plugins/darkroom/colortransfer.svg
/usr/share/darktable/pixmaps/plugins/darkroom/colorzones.png
/usr/share/darktable/pixmaps/plugins/darkroom/colorzones.svg
/usr/share/darktable/pixmaps/plugins/darkroom/default.svg
/usr/share/darktable/pixmaps/plugins/darkroom/demosaic.png
/usr/share/darktable/pixmaps/plugins/darkroom/demosaic.svg
/usr/share/darktable/pixmaps/plugins/darkroom/dither.png
/usr/share/darktable/pixmaps/plugins/darkroom/dither.svg
/usr/share/darktable/pixmaps/plugins/darkroom/exposure.png
/usr/share/darktable/pixmaps/plugins/darkroom/exposure.svg
/usr/share/darktable/pixmaps/plugins/darkroom/flip.png
/usr/share/darktable/pixmaps/plugins/darkroom/flip.svg
/usr/share/darktable/pixmaps/plugins/darkroom/graduatednd.png
/usr/share/darktable/pixmaps/plugins/darkroom/graduatednd.svg
/usr/share/darktable/pixmaps/plugins/darkroom/grain.png
/usr/share/darktable/pixmaps/plugins/darkroom/grain.svg
/usr/share/darktable/pixmaps/plugins/darkroom/hazeremoval.png
/usr/share/darktable/pixmaps/plugins/darkroom/hazeremoval.svg
/usr/share/darktable/pixmaps/plugins/darkroom/highlights.png
/usr/share/darktable/pixmaps/plugins/darkroom/highlights.svg
/usr/share/darktable/pixmaps/plugins/darkroom/highpass.png
/usr/share/darktable/pixmaps/plugins/darkroom/highpass.svg
/usr/share/darktable/pixmaps/plugins/darkroom/hotpixels.png
/usr/share/darktable/pixmaps/plugins/darkroom/hotpixels.svg
/usr/share/darktable/pixmaps/plugins/darkroom/invert.png
/usr/share/darktable/pixmaps/plugins/darkroom/invert.svg
/usr/share/darktable/pixmaps/plugins/darkroom/lens.png
/usr/share/darktable/pixmaps/plugins/darkroom/lens.svg
/usr/share/darktable/pixmaps/plugins/darkroom/levels.png
/usr/share/darktable/pixmaps/plugins/darkroom/levels.svg
/usr/share/darktable/pixmaps/plugins/darkroom/liquify.png
/usr/share/darktable/pixmaps/plugins/darkroom/liquify.svg
/usr/share/darktable/pixmaps/plugins/darkroom/lowlight.png
/usr/share/darktable/pixmaps/plugins/darkroom/lowlight.svg
/usr/share/darktable/pixmaps/plugins/darkroom/lowpass.png
/usr/share/darktable/pixmaps/plugins/darkroom/lowpass.svg
/usr/share/darktable/pixmaps/plugins/darkroom/monochrome.png
/usr/share/darktable/pixmaps/plugins/darkroom/monochrome.svg
/usr/share/darktable/pixmaps/plugins/darkroom/nlmeans.png
/usr/share/darktable/pixmaps/plugins/darkroom/nlmeans.svg
/usr/share/darktable/pixmaps/plugins/darkroom/overexposed.png
/usr/share/darktable/pixmaps/plugins/darkroom/overexposed.svg
/usr/share/darktable/pixmaps/plugins/darkroom/profile_gamma.png
/usr/share/darktable/pixmaps/plugins/darkroom/profile_gamma.svg
/usr/share/darktable/pixmaps/plugins/darkroom/rawdenoise.png
/usr/share/darktable/pixmaps/plugins/darkroom/rawdenoise.svg
/usr/share/darktable/pixmaps/plugins/darkroom/rawimport.png
/usr/share/darktable/pixmaps/plugins/darkroom/rawimport.svg
/usr/share/darktable/pixmaps/plugins/darkroom/rawprepare.png
/usr/share/darktable/pixmaps/plugins/darkroom/rawprepare.svg
/usr/share/darktable/pixmaps/plugins/darkroom/relight.png
/usr/share/darktable/pixmaps/plugins/darkroom/relight.svg
/usr/share/darktable/pixmaps/plugins/darkroom/shadhi.png
/usr/share/darktable/pixmaps/plugins/darkroom/shadhi.svg
/usr/share/darktable/pixmaps/plugins/darkroom/sharpen.png
/usr/share/darktable/pixmaps/plugins/darkroom/sharpen.svg
/usr/share/darktable/pixmaps/plugins/darkroom/soften.png
/usr/share/darktable/pixmaps/plugins/darkroom/soften.svg
/usr/share/darktable/pixmaps/plugins/darkroom/splittoning.png
/usr/share/darktable/pixmaps/plugins/darkroom/splittoning.svg
/usr/share/darktable/pixmaps/plugins/darkroom/spots.png
/usr/share/darktable/pixmaps/plugins/darkroom/spots.svg
/usr/share/darktable/pixmaps/plugins/darkroom/temperature.png
/usr/share/darktable/pixmaps/plugins/darkroom/temperature.svg
/usr/share/darktable/pixmaps/plugins/darkroom/template.png
/usr/share/darktable/pixmaps/plugins/darkroom/template.svg
/usr/share/darktable/pixmaps/plugins/darkroom/tonecurve.png
/usr/share/darktable/pixmaps/plugins/darkroom/tonecurve.svg
/usr/share/darktable/pixmaps/plugins/darkroom/tonemap.png
/usr/share/darktable/pixmaps/plugins/darkroom/tonemap.svg
/usr/share/darktable/pixmaps/plugins/darkroom/velvia.png
/usr/share/darktable/pixmaps/plugins/darkroom/velvia.svg
/usr/share/darktable/pixmaps/plugins/darkroom/vignette.png
/usr/share/darktable/pixmaps/plugins/darkroom/vignette.svg
/usr/share/darktable/pixmaps/plugins/darkroom/watermark.png
/usr/share/darktable/pixmaps/plugins/darkroom/watermark.svg
/usr/share/darktable/pixmaps/plugins/darkroom/zonesystem.png
/usr/share/darktable/pixmaps/plugins/darkroom/zonesystem.svg
/usr/share/darktable/pixmaps/splashscreen-01.jpg
/usr/share/darktable/pixmaps/splashscreen-02.jpg
/usr/share/darktable/pixmaps/splashscreen-03.jpg
/usr/share/darktable/pixmaps/splashscreen-04.jpg
/usr/share/darktable/pixmaps/splashscreen.png
/usr/share/darktable/pswp/LICENSE
/usr/share/darktable/pswp/default-skin/default-skin.css
/usr/share/darktable/pswp/default-skin/default-skin.png
/usr/share/darktable/pswp/default-skin/default-skin.svg
/usr/share/darktable/pswp/default-skin/preloader.gif
/usr/share/darktable/pswp/photoswipe-ui-default.js
/usr/share/darktable/pswp/photoswipe-ui-default.min.js
/usr/share/darktable/pswp/photoswipe.css
/usr/share/darktable/pswp/photoswipe.js
/usr/share/darktable/pswp/photoswipe.min.js
/usr/share/darktable/rawspeed/cameras.xml
/usr/share/darktable/rawspeed/showcameras.xsl
/usr/share/darktable/style/bullet.gif
/usr/share/darktable/style/close.gif
/usr/share/darktable/style/closelabel.gif
/usr/share/darktable/style/donate-button.gif
/usr/share/darktable/style/download-icon.gif
/usr/share/darktable/style/favicon.ico
/usr/share/darktable/style/image-1.jpg
/usr/share/darktable/style/lightbox.css
/usr/share/darktable/style/loading.gif
/usr/share/darktable/style/nextlabel.gif
/usr/share/darktable/style/prevlabel.gif
/usr/share/darktable/style/style.css
/usr/share/darktable/style/thumb-1.jpg
"/usr/share/darktable/styles/darktable_Canon_EOS 10D.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS 1100D.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS 2000D.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS 4000D.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS 5D Mark II.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS 5D Mark III.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS 5D Mark IV.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS 5D.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS 60D.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS 6D.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS 70D.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS 7D Mark II.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS 7D.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS 80D.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS D30.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS Digital Rebel XT.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS Kiss Digital N.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS Kiss M.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS Kiss X3.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS M.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS M10.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS M2.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS M3.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS M50 Mark II.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS M50.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS M6.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS R-series.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS R3.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS R50.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS R6 Mark II.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS R6.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS R7.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS RP.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS Rebel SL1.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS Rebel T3.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS Rebel T5.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS Rebel T_ series.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS _200D Mark II,250D_.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS-1D Mark II.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS-1D Mark IV.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS-1D X Mark _II,III_.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_EOS-1D X.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_PowerShot G1.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_PowerShot G10.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_PowerShot G11.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_PowerShot G15.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_PowerShot G16.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_PowerShot G2.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_PowerShot G3.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_PowerShot G5 X Mark II.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_PowerShot G5 X.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_PowerShot G5.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_PowerShot G6.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_PowerShot G7 X Mark III.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_PowerShot G9 X Mark II.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_PowerShot G9.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_PowerShot S110.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_PowerShot S95.dtstyle"
"/usr/share/darktable/styles/darktable_Canon_PowerShot SX70 HS.dtstyle"
/usr/share/darktable/styles/darktable_Canon__l10n_generic.dtstyle
"/usr/share/darktable/styles/darktable_DJI_DJI Osmo Action.dtstyle"
/usr/share/darktable/styles/darktable_DJI_FC350.dtstyle
/usr/share/darktable/styles/darktable_DJI_FC7303.dtstyle
/usr/share/darktable/styles/darktable_Epson_R-D1.dtstyle
/usr/share/darktable/styles/darktable_Epson_R-D1x.dtstyle
"/usr/share/darktable/styles/darktable_Fujifilm_FinePix E550.dtstyle"
"/usr/share/darktable/styles/darktable_Fujifilm_FinePix E900.dtstyle"
"/usr/share/darktable/styles/darktable_Fujifilm_FinePix F600EXR.dtstyle"
"/usr/share/darktable/styles/darktable_Fujifilm_FinePix F770EXR.dtstyle"
"/usr/share/darktable/styles/darktable_Fujifilm_FinePix HS30EXR.dtstyle"
"/usr/share/darktable/styles/darktable_Fujifilm_FinePix S5000.dtstyle"
"/usr/share/darktable/styles/darktable_Fujifilm_FinePix S5Pro.dtstyle"
"/usr/share/darktable/styles/darktable_Fujifilm_FinePix S6000fd.dtstyle"
"/usr/share/darktable/styles/darktable_Fujifilm_FinePix X10.dtstyle"
"/usr/share/darktable/styles/darktable_Fujifilm_FinePix X100.dtstyle"
"/usr/share/darktable/styles/darktable_Fujifilm_GFX 100.dtstyle"
"/usr/share/darktable/styles/darktable_Fujifilm_GFX 50R.dtstyle"
"/usr/share/darktable/styles/darktable_Fujifilm_GFX 50S.dtstyle"
"/usr/share/darktable/styles/darktable_Fujifilm_GFX100 II.dtstyle"
/usr/share/darktable/styles/darktable_Fujifilm_X-A1.dtstyle
/usr/share/darktable/styles/darktable_Fujifilm_X-A2.dtstyle
/usr/share/darktable/styles/darktable_Fujifilm_X-A5.dtstyle
"/usr/share/darktable/styles/darktable_Fujifilm_X-A_ series.dtstyle"
/usr/share/darktable/styles/darktable_Fujifilm_X-E1.dtstyle
"/usr/share/darktable/styles/darktable_Fujifilm_X-E_ series.dtstyle"
"/usr/share/darktable/styles/darktable_Fujifilm_X-H_ series.dtstyle"
/usr/share/darktable/styles/darktable_Fujifilm_X-M1.dtstyle
/usr/share/darktable/styles/darktable_Fujifilm_X-Pro1.dtstyle
"/usr/share/darktable/styles/darktable_Fujifilm_X-Pro_ series.dtstyle"
/usr/share/darktable/styles/darktable_Fujifilm_X-S1.dtstyle
/usr/share/darktable/styles/darktable_Fujifilm_X-S10.dtstyle
/usr/share/darktable/styles/darktable_Fujifilm_X-S20.dtstyle
/usr/share/darktable/styles/darktable_Fujifilm_X-T10.dtstyle
/usr/share/darktable/styles/darktable_Fujifilm_X-T100.dtstyle
/usr/share/darktable/styles/darktable_Fujifilm_X-T2.dtstyle
/usr/share/darktable/styles/darktable_Fujifilm_X-T3.dtstyle
/usr/share/darktable/styles/darktable_Fujifilm_X-T5.dtstyle
/usr/share/darktable/styles/darktable_Fujifilm_X100F.dtstyle
/usr/share/darktable/styles/darktable_Fujifilm_X100S.dtstyle
/usr/share/darktable/styles/darktable_Fujifilm_X100T.dtstyle
/usr/share/darktable/styles/darktable_Fujifilm_X100V.dtstyle
/usr/share/darktable/styles/darktable_Fujifilm_X20.dtstyle
/usr/share/darktable/styles/darktable_Fujifilm_X30.dtstyle
/usr/share/darktable/styles/darktable_Fujifilm_X70.dtstyle
/usr/share/darktable/styles/darktable_Fujifilm_XF1.dtstyle
/usr/share/darktable/styles/darktable_Fujifilm_XQ1.dtstyle
/usr/share/darktable/styles/darktable_Fujifilm_XQ2.dtstyle
/usr/share/darktable/styles/darktable_Fujifilm__l10n_generic.dtstyle
/usr/share/darktable/styles/darktable_Hasselblad_CFV.dtstyle
/usr/share/darktable/styles/darktable_Hasselblad_H3D.dtstyle
/usr/share/darktable/styles/darktable_Hasselblad_X1D.dtstyle
/usr/share/darktable/styles/darktable_Hasselblad__l10n_generic.dtstyle
"/usr/share/darktable/styles/darktable_Leaf_Credo 40.dtstyle"
"/usr/share/darktable/styles/darktable_Leica_C (Typ 112).dtstyle"
/usr/share/darktable/styles/darktable_Leica_C-Lux.dtstyle
"/usr/share/darktable/styles/darktable_Leica_D-LUX (Typ 109).dtstyle"
"/usr/share/darktable/styles/darktable_Leica_D-LUX 5.dtstyle"
"/usr/share/darktable/styles/darktable_Leica_D-LUX 6.dtstyle"
"/usr/share/darktable/styles/darktable_Leica_D-Lux 7.dtstyle"
"/usr/share/darktable/styles/darktable_Leica_M Monochrom (Typ 246).dtstyle"
/usr/share/darktable/styles/darktable_Leica_M9.dtstyle
"/usr/share/darktable/styles/darktable_Leica_Q (Typ 116).dtstyle"
/usr/share/darktable/styles/darktable_Leica_Q2.dtstyle
"/usr/share/darktable/styles/darktable_Leica_SL (Typ 601).dtstyle"
"/usr/share/darktable/styles/darktable_Leica_V-LUX (Typ 114).dtstyle"
"/usr/share/darktable/styles/darktable_Leica_V-Lux 4.dtstyle"
/usr/share/darktable/styles/darktable_Leica_X2.dtstyle
/usr/share/darktable/styles/darktable_Minolta_A2.dtstyle
"/usr/share/darktable/styles/darktable_Minolta_DiMAGE 7.dtstyle"
"/usr/share/darktable/styles/darktable_Minolta_DiMAGE 7Hi.dtstyle"
"/usr/share/darktable/styles/darktable_Minolta_DiMAGE 7i.dtstyle"
"/usr/share/darktable/styles/darktable_Minolta_DiMAGE A1.dtstyle"
"/usr/share/darktable/styles/darktable_Minolta_DiMAGE A200.dtstyle"
"/usr/share/darktable/styles/darktable_Minolta_Dynax 5D.dtstyle"
"/usr/share/darktable/styles/darktable_Minolta_Dynax 7D.dtstyle"
"/usr/share/darktable/styles/darktable_Minolta_Maxxum 7D.dtstyle"
"/usr/share/darktable/styles/darktable_Nikon_1 AW1.dtstyle"
"/usr/share/darktable/styles/darktable_Nikon_1 J1.dtstyle"
"/usr/share/darktable/styles/darktable_Nikon_1 J2.dtstyle"
"/usr/share/darktable/styles/darktable_Nikon_1 J3.dtstyle"
"/usr/share/darktable/styles/darktable_Nikon_1 J4.dtstyle"
"/usr/share/darktable/styles/darktable_Nikon_1 JS.dtstyle"
"/usr/share/darktable/styles/darktable_Nikon_1 S1.dtstyle"
"/usr/share/darktable/styles/darktable_Nikon_1 V1.dtstyle"
"/usr/share/darktable/styles/darktable_Nikon_1 V2.dtstyle"
"/usr/share/darktable/styles/darktable_Nikon_1 V3.dtstyle"
"/usr/share/darktable/styles/darktable_Nikon_COOLPIX B700.dtstyle"
"/usr/share/darktable/styles/darktable_Nikon_COOLPIX P1000.dtstyle"
"/usr/share/darktable/styles/darktable_Nikon_COOLPIX P950.dtstyle"
"/usr/share/darktable/styles/darktable_Nikon_Coolpix A.dtstyle"
"/usr/share/darktable/styles/darktable_Nikon_Coolpix A1000.dtstyle"
"/usr/share/darktable/styles/darktable_Nikon_Coolpix P330.dtstyle"
"/usr/share/darktable/styles/darktable_Nikon_Coolpix P6000.dtstyle"
"/usr/share/darktable/styles/darktable_Nikon_Coolpix P7700.dtstyle"
"/usr/share/darktable/styles/darktable_Nikon_Coolpix P7800.dtstyle"
/usr/share/darktable/styles/darktable_Nikon_D1.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D100.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D1H.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D1X.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D200.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D2H.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D2X.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D3.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D300.dtstyle
"/usr/share/darktable/styles/darktable_Nikon_D3000 series.dtstyle"
/usr/share/darktable/styles/darktable_Nikon_D300S.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D3100.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D3200.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D3300.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D3400.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D3500.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D3S.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D3X.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D4.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D40.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D40X.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D4S.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D5.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D50.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D500.dtstyle
"/usr/share/darktable/styles/darktable_Nikon_D5000 series.dtstyle"
/usr/share/darktable/styles/darktable_Nikon_D5100.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D5200.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D5500.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D6.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D60.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D600.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D610.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D70.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D700.dtstyle
"/usr/share/darktable/styles/darktable_Nikon_D7000 series.dtstyle"
/usr/share/darktable/styles/darktable_Nikon_D7000.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D70s.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D7200.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D750.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D7500.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D780.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D80.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D800.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D800E.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D810.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D850.dtstyle
/usr/share/darktable/styles/darktable_Nikon_D90.dtstyle
/usr/share/darktable/styles/darktable_Nikon_Df.dtstyle
/usr/share/darktable/styles/darktable_Nikon_E5400.dtstyle
/usr/share/darktable/styles/darktable_Nikon_E5700.dtstyle
"/usr/share/darktable/styles/darktable_Nikon_Z 30.dtstyle"
"/usr/share/darktable/styles/darktable_Nikon_Z 5.dtstyle"
"/usr/share/darktable/styles/darktable_Nikon_Z 50.dtstyle"
"/usr/share/darktable/styles/darktable_Nikon_Z 6.dtstyle"
"/usr/share/darktable/styles/darktable_Nikon_Z 6_2.dtstyle"
"/usr/share/darktable/styles/darktable_Nikon_Z 7.dtstyle"
"/usr/share/darktable/styles/darktable_Nikon_Z 7_2.dtstyle"
"/usr/share/darktable/styles/darktable_Nikon_Z 8.dtstyle"
"/usr/share/darktable/styles/darktable_Nikon_Z 9.dtstyle"
"/usr/share/darktable/styles/darktable_Nikon_Z f.dtstyle"
"/usr/share/darktable/styles/darktable_Nikon_Z series.dtstyle"
/usr/share/darktable/styles/darktable_Nikon_Z50_2.dtstyle
/usr/share/darktable/styles/darktable_Nikon_Z6_3.dtstyle
/usr/share/darktable/styles/darktable_Nikon__l10n_generic.dtstyle
"/usr/share/darktable/styles/darktable_OM System_OM-1 Mark II.dtstyle"
"/usr/share/darktable/styles/darktable_OM System_OM-1.dtstyle"
"/usr/share/darktable/styles/darktable_OM System_OM-5.dtstyle"
"/usr/share/darktable/styles/darktable_OM System_TG-7.dtstyle"
/usr/share/darktable/styles/darktable_Olympus_C7070WZ.dtstyle
/usr/share/darktable/styles/darktable_Olympus_E-1.dtstyle
/usr/share/darktable/styles/darktable_Olympus_E-3.dtstyle
/usr/share/darktable/styles/darktable_Olympus_E-300.dtstyle
/usr/share/darktable/styles/darktable_Olympus_E-330.dtstyle
/usr/share/darktable/styles/darktable_Olympus_E-400.dtstyle
/usr/share/darktable/styles/darktable_Olympus_E-5.dtstyle
/usr/share/darktable/styles/darktable_Olympus_E-500.dtstyle
/usr/share/darktable/styles/darktable_Olympus_E-620.dtstyle
/usr/share/darktable/styles/darktable_Olympus_E-M1.dtstyle
"/usr/share/darktable/styles/darktable_Olympus_E-M10 Mark II.dtstyle"
"/usr/share/darktable/styles/darktable_Olympus_E-M10 Mark III.dtstyle"
"/usr/share/darktable/styles/darktable_Olympus_E-M10 Mark IIIs.dtstyle"
"/usr/share/darktable/styles/darktable_Olympus_E-M10 Mark IV.dtstyle"
/usr/share/darktable/styles/darktable_Olympus_E-M10.dtstyle
/usr/share/darktable/styles/darktable_Olympus_E-M1MarkII.dtstyle
/usr/share/darktable/styles/darktable_Olympus_E-M1MarkIII.dtstyle
/usr/share/darktable/styles/darktable_Olympus_E-M1X.dtstyle
"/usr/share/darktable/styles/darktable_Olympus_E-M5 Mark II.dtstyle"
"/usr/share/darktable/styles/darktable_Olympus_E-M5 Mark III.dtstyle"
/usr/share/darktable/styles/darktable_Olympus_E-M5.dtstyle
/usr/share/darktable/styles/darktable_Olympus_E-P1.dtstyle
/usr/share/darktable/styles/darktable_Olympus_E-P5.dtstyle
/usr/share/darktable/styles/darktable_Olympus_E-P7.dtstyle
/usr/share/darktable/styles/darktable_Olympus_E-PL1.dtstyle
/usr/share/darktable/styles/darktable_Olympus_E-PL10.dtstyle
/usr/share/darktable/styles/darktable_Olympus_E-PL2.dtstyle
/usr/share/darktable/styles/darktable_Olympus_E-PL7.dtstyle
"/usr/share/darktable/styles/darktable_Olympus_E-PL_ series.dtstyle"
/usr/share/darktable/styles/darktable_Olympus_E-PM1.dtstyle
/usr/share/darktable/styles/darktable_Olympus_PEN-F.dtstyle
/usr/share/darktable/styles/darktable_Olympus_SH-2.dtstyle
/usr/share/darktable/styles/darktable_Olympus_Stylus1.dtstyle
/usr/share/darktable/styles/darktable_Olympus_TG-4.dtstyle
/usr/share/darktable/styles/darktable_Olympus_TG-5.dtstyle
/usr/share/darktable/styles/darktable_Olympus_TG-6.dtstyle
/usr/share/darktable/styles/darktable_Olympus_XZ-1.dtstyle
/usr/share/darktable/styles/darktable_Olympus_XZ-2.dtstyle
/usr/share/darktable/styles/darktable_OnePlus_One.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DC-FZ10002.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DC-FZ80.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DC-FZ82.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DC-G100.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DC-G110.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DC-G9.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DC-G90.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DC-G91.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DC-G95.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DC-G95D.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DC-GH5.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DC-GH5M2.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DC-GH5S.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DC-GX7MK3.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DC-GX800.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DC-GX850.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DC-GX880.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DC-GX9.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DC-LX100M2.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DC-S1.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DC-S1H.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DC-S1R.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DC-S5.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DC-TZ200.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DC-TZ200D.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DC-TZ202.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DC-TZ90.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DC-TZ91.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DC-TZ95.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DC-TZ95D.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DC-TZ96.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DC-ZS200D.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-FZ100.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-FZ1000.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-FZ150.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-FZ18.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-FZ200.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-FZ2000.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-FZ2500.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-FZ28.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-FZ300.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-FZ330.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-FZ35.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-FZ38.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-FZ45.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-G1.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-G10.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-G2.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-G3.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-G5.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-G6.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-G7.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-G70.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-G80.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-G81.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-G85.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-GF1.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-GF2.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-GF3.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-GF6.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-GF7.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-GF8.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-GH1.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-GH2.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-GH3.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-GH4.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-GM1.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-GM1S.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-GX1.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-GX7.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-GX7MK2.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-GX8.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-GX80.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-GX85.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-LF1.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-LX10.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-LX100.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-LX15.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-LX3.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-LX5.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-LX7.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-TX1.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-TZ100.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-TZ101.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-TZ110.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-TZ61.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-TZ70.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-TZ71.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-TZ80.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-TZ81.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-ZS100.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-ZS40.dtstyle
/usr/share/darktable/styles/darktable_Panasonic_DMC-ZS60.dtstyle
/usr/share/darktable/styles/darktable_Pentax_645D.dtstyle
/usr/share/darktable/styles/darktable_Pentax_645Z.dtstyle
/usr/share/darktable/styles/darktable_Pentax_K-01.dtstyle
"/usr/share/darktable/styles/darktable_Pentax_K-1 Mark II.dtstyle"
/usr/share/darktable/styles/darktable_Pentax_K-1.dtstyle
"/usr/share/darktable/styles/darktable_Pentax_K-3 II.dtstyle"
"/usr/share/darktable/styles/darktable_Pentax_K-3 Mark III.dtstyle"
/usr/share/darktable/styles/darktable_Pentax_K-3.dtstyle
/usr/share/darktable/styles/darktable_Pentax_K-30.dtstyle
"/usr/share/darktable/styles/darktable_Pentax_K-5 II s.dtstyle"
"/usr/share/darktable/styles/darktable_Pentax_K-5 II.dtstyle"
/usr/share/darktable/styles/darktable_Pentax_K-5.dtstyle
/usr/share/darktable/styles/darktable_Pentax_K-50.dtstyle
/usr/share/darktable/styles/darktable_Pentax_K-500.dtstyle
/usr/share/darktable/styles/darktable_Pentax_K-S1.dtstyle
/usr/share/darktable/styles/darktable_Pentax_K-S2.dtstyle
/usr/share/darktable/styles/darktable_Pentax_K-m.dtstyle
/usr/share/darktable/styles/darktable_Pentax_K-r.dtstyle
/usr/share/darktable/styles/darktable_Pentax_K1000.dtstyle
"/usr/share/darktable/styles/darktable_Pentax_K100D Super.dtstyle"
/usr/share/darktable/styles/darktable_Pentax_K10D.dtstyle
/usr/share/darktable/styles/darktable_Pentax_K110D.dtstyle
/usr/share/darktable/styles/darktable_Pentax_K2000.dtstyle
/usr/share/darktable/styles/darktable_Pentax_K200D.dtstyle
/usr/share/darktable/styles/darktable_Pentax_K20D.dtstyle
/usr/share/darktable/styles/darktable_Pentax_KF.dtstyle
/usr/share/darktable/styles/darktable_Pentax_KP.dtstyle
/usr/share/darktable/styles/darktable_Pentax_Q.dtstyle
/usr/share/darktable/styles/darktable_Pentax_Q7.dtstyle
"/usr/share/darktable/styles/darktable_Pentax__ist D.dtstyle"
"/usr/share/darktable/styles/darktable_Pentax__ist DL.dtstyle"
"/usr/share/darktable/styles/darktable_Pentax__ist DS.dtstyle"
"/usr/share/darktable/styles/darktable_Phase One_IQ180.dtstyle"
"/usr/share/darktable/styles/darktable_Phase One_P65+.dtstyle"
/usr/share/darktable/styles/darktable_Samsung_EK-GN120.dtstyle
/usr/share/darktable/styles/darktable_Samsung_EX2F.dtstyle
/usr/share/darktable/styles/darktable_Samsung_G935F.dtstyle
/usr/share/darktable/styles/darktable_Samsung_GX10.dtstyle
"/usr/share/darktable/styles/darktable_Samsung_NX mini.dtstyle"
/usr/share/darktable/styles/darktable_Samsung_NX1.dtstyle
/usr/share/darktable/styles/darktable_Samsung_NX10.dtstyle
/usr/share/darktable/styles/darktable_Samsung_NX11.dtstyle
/usr/share/darktable/styles/darktable_Samsung_NX1100.dtstyle
/usr/share/darktable/styles/darktable_Samsung_NX20.dtstyle
/usr/share/darktable/styles/darktable_Samsung_NX200.dtstyle
/usr/share/darktable/styles/darktable_Samsung_NX2000.dtstyle
/usr/share/darktable/styles/darktable_Samsung_NX210.dtstyle
/usr/share/darktable/styles/darktable_Samsung_NX30.dtstyle
/usr/share/darktable/styles/darktable_Samsung_NX300.dtstyle
/usr/share/darktable/styles/darktable_Samsung_NX3000.dtstyle
/usr/share/darktable/styles/darktable_Samsung_NX300M.dtstyle
/usr/share/darktable/styles/darktable_Samsung_NX3300.dtstyle
/usr/share/darktable/styles/darktable_Samsung_NX5.dtstyle
/usr/share/darktable/styles/darktable_Samsung_NX500.dtstyle
/usr/share/darktable/styles/darktable_Samsung_WB2000.dtstyle
"/usr/share/darktable/styles/darktable_Sigma_fp L.dtstyle"
/usr/share/darktable/styles/darktable_Sigma_fp.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSC-F828.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSC-HX95.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSC-HX99.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSC-R1.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSC-RX0.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSC-RX0M2.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSC-RX1.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSC-RX10.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSC-RX100.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSC-RX100M2.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSC-RX100M3.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSC-RX100M4.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSC-RX100M5.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSC-RX100M5A.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSC-RX100M6.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSC-RX100M7.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSC-RX10M2.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSC-RX10M3.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSC-RX10M4.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSC-RX1R.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSC-RX1RM2.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSLR-A100.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSLR-A200.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSLR-A230.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSLR-A290.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSLR-A300.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSLR-A330.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSLR-A350.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSLR-A380.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSLR-A390.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSLR-A450.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSLR-A500.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSLR-A550.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSLR-A560.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSLR-A580.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSLR-A700.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSLR-A850.dtstyle
/usr/share/darktable/styles/darktable_Sony_DSLR-A900.dtstyle
/usr/share/darktable/styles/darktable_Sony_ILCA-68.dtstyle
/usr/share/darktable/styles/darktable_Sony_ILCA-77M2.dtstyle
/usr/share/darktable/styles/darktable_Sony_ILCA-99M2.dtstyle
/usr/share/darktable/styles/darktable_Sony_ILCE-1.dtstyle
/usr/share/darktable/styles/darktable_Sony_ILCE-3000.dtstyle
/usr/share/darktable/styles/darktable_Sony_ILCE-3500.dtstyle
/usr/share/darktable/styles/darktable_Sony_ILCE-5000.dtstyle
/usr/share/darktable/styles/darktable_Sony_ILCE-5100.dtstyle
/usr/share/darktable/styles/darktable_Sony_ILCE-6000.dtstyle
/usr/share/darktable/styles/darktable_Sony_ILCE-6100.dtstyle
/usr/share/darktable/styles/darktable_Sony_ILCE-6300.dtstyle
/usr/share/darktable/styles/darktable_Sony_ILCE-6400.dtstyle
/usr/share/darktable/styles/darktable_Sony_ILCE-6500.dtstyle
/usr/share/darktable/styles/darktable_Sony_ILCE-6600.dtstyle
/usr/share/darktable/styles/darktable_Sony_ILCE-6700.dtstyle
/usr/share/darktable/styles/darktable_Sony_ILCE-7.dtstyle
/usr/share/darktable/styles/darktable_Sony_ILCE-7C.dtstyle
/usr/share/darktable/styles/darktable_Sony_ILCE-7CM2.dtstyle
/usr/share/darktable/styles/darktable_Sony_ILCE-7CR.dtstyle
/usr/share/darktable/styles/darktable_Sony_ILCE-7M2.dtstyle
/usr/share/darktable/styles/darktable_Sony_ILCE-7M3.dtstyle
/usr/share/darktable/styles/darktable_Sony_ILCE-7M4.dtstyle
/usr/share/darktable/styles/darktable_Sony_ILCE-7R.dtstyle
/usr/share/darktable/styles/darktable_Sony_ILCE-7RM2.dtstyle
/usr/share/darktable/styles/darktable_Sony_ILCE-7RM3.dtstyle
/usr/share/darktable/styles/darktable_Sony_ILCE-7RM4.dtstyle
/usr/share/darktable/styles/darktable_Sony_ILCE-7RM4A.dtstyle
/usr/share/darktable/styles/darktable_Sony_ILCE-7RM5.dtstyle
/usr/share/darktable/styles/darktable_Sony_ILCE-7S.dtstyle
/usr/share/darktable/styles/darktable_Sony_ILCE-7SM2.dtstyle
/usr/share/darktable/styles/darktable_Sony_ILCE-7SM3.dtstyle
"/usr/share/darktable/styles/darktable_Sony_ILCE-9 series.dtstyle"
/usr/share/darktable/styles/darktable_Sony_ILCE-9.dtstyle
/usr/share/darktable/styles/darktable_Sony_ILCE-9M3.dtstyle
/usr/share/darktable/styles/darktable_Sony_ILCE-QX1.dtstyle
/usr/share/darktable/styles/darktable_Sony_ILME-FX3.dtstyle
/usr/share/darktable/styles/darktable_Sony_ILME-FX30.dtstyle
/usr/share/darktable/styles/darktable_Sony_NEX-3N.dtstyle
/usr/share/darktable/styles/darktable_Sony_NEX-5.dtstyle
/usr/share/darktable/styles/darktable_Sony_NEX-5N.dtstyle
/usr/share/darktable/styles/darktable_Sony_NEX-5R.dtstyle
/usr/share/darktable/styles/darktable_Sony_NEX-5T.dtstyle
/usr/share/darktable/styles/darktable_Sony_NEX-6.dtstyle
/usr/share/darktable/styles/darktable_Sony_NEX-C3.dtstyle
/usr/share/darktable/styles/darktable_Sony_NEX-F3.dtstyle
/usr/share/darktable/styles/darktable_Sony_SLT-A33.dtstyle
/usr/share/darktable/styles/darktable_Sony_SLT-A35.dtstyle
/usr/share/darktable/styles/darktable_Sony_SLT-A37.dtstyle
/usr/share/darktable/styles/darktable_Sony_SLT-A55.dtstyle
/usr/share/darktable/styles/darktable_Sony_SLT-A57.dtstyle
/usr/share/darktable/styles/darktable_Sony_SLT-A58.dtstyle
/usr/share/darktable/styles/darktable_Sony_SLT-A65.dtstyle
/usr/share/darktable/styles/darktable_Sony_SLT-A77.dtstyle
/usr/share/darktable/styles/darktable_Sony_SLT-A99.dtstyle
/usr/share/darktable/styles/darktable_Sony_UMC-R10C.dtstyle
/usr/share/darktable/styles/darktable_Sony_ZV-1.dtstyle
/usr/share/darktable/styles/darktable_Sony_ZV-E1.dtstyle
/usr/share/darktable/styles/darktable_Sony_ZV-E10.dtstyle
/usr/share/darktable/styles/darktable__l10n_generic.dtstyle
/usr/share/darktable/themes/darktable-elegant-dark.css
/usr/share/darktable/themes/darktable-elegant-darker.css
/usr/share/darktable/themes/darktable-elegant-grey.css
/usr/share/darktable/themes/darktable-elegant-highcontrast.css
/usr/share/darktable/themes/darktable-icons-dark.css
/usr/share/darktable/themes/darktable-icons-darker.css
/usr/share/darktable/themes/darktable-icons-grey.css
/usr/share/darktable/themes/darktable-icons-highcontrast.css
/usr/share/darktable/themes/darktable-icons.css
/usr/share/darktable/themes/darktable.css
/usr/share/darktable/tools/common.sh
/usr/share/darktable/tools/extract_wb_from_images.sh
/usr/share/darktable/tools/purge_from_cache.sh
/usr/share/darktable/tools/purge_non_existing_images.sh
/usr/share/darktable/tools/purge_unused_tags.sh
/usr/share/darktable/watermarks/darktable.svg
/usr/share/darktable/watermarks/fixed-size-text.svg
/usr/share/darktable/watermarks/hasselblad.svg
/usr/share/darktable/watermarks/metadata-template.svg
/usr/share/darktable/watermarks/promo.svg
/usr/share/darktable/watermarks/simple-text-shadow.svg
/usr/share/darktable/watermarks/simple-text.svg
/usr/share/darktable/wb_presets.json
/usr/share/icons/hicolor/16x16/apps/darktable.png
/usr/share/icons/hicolor/22x22/apps/darktable.png
/usr/share/icons/hicolor/24x24/apps/darktable.png
/usr/share/icons/hicolor/256x256/apps/darktable.png
/usr/share/icons/hicolor/32x32/apps/darktable.png
/usr/share/icons/hicolor/48x48/apps/darktable.png
/usr/share/icons/hicolor/64x64/apps/darktable.png
/usr/share/icons/hicolor/scalable/apps/darktable-1.svg
/usr/share/icons/hicolor/scalable/apps/darktable-2.svg
/usr/share/icons/hicolor/scalable/apps/darktable-3.svg
/usr/share/icons/hicolor/scalable/apps/darktable.svg
/usr/share/icons/hicolor/scalable/apps/darktable_macos_icon.svg
/usr/share/metainfo/org.darktable.darktable.appdata.xml

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/darktable/*

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/darktable/libdarktable.so
/V3/usr/lib64/darktable/plugins/imageio/format/libavif.so
/V3/usr/lib64/darktable/plugins/imageio/format/libcopy.so
/V3/usr/lib64/darktable/plugins/imageio/format/libexr.so
/V3/usr/lib64/darktable/plugins/imageio/format/libj2k.so
/V3/usr/lib64/darktable/plugins/imageio/format/libjpeg.so
/V3/usr/lib64/darktable/plugins/imageio/format/libpdf.so
/V3/usr/lib64/darktable/plugins/imageio/format/libpfm.so
/V3/usr/lib64/darktable/plugins/imageio/format/libpng.so
/V3/usr/lib64/darktable/plugins/imageio/format/libppm.so
/V3/usr/lib64/darktable/plugins/imageio/format/libtiff.so
/V3/usr/lib64/darktable/plugins/imageio/format/libwebp.so
/V3/usr/lib64/darktable/plugins/imageio/format/libxcf.so
/V3/usr/lib64/darktable/plugins/imageio/storage/libdisk.so
/V3/usr/lib64/darktable/plugins/imageio/storage/libemail.so
/V3/usr/lib64/darktable/plugins/imageio/storage/libgallery.so
/V3/usr/lib64/darktable/plugins/imageio/storage/liblatex.so
/V3/usr/lib64/darktable/plugins/imageio/storage/libpiwigo.so
/V3/usr/lib64/darktable/plugins/libashift.so
/V3/usr/lib64/darktable/plugins/libatrous.so
/V3/usr/lib64/darktable/plugins/libbasecurve.so
/V3/usr/lib64/darktable/plugins/libbasicadj.so
/V3/usr/lib64/darktable/plugins/libbilat.so
/V3/usr/lib64/darktable/plugins/libbilateral.so
/V3/usr/lib64/darktable/plugins/libbloom.so
/V3/usr/lib64/darktable/plugins/libblurs.so
/V3/usr/lib64/darktable/plugins/libborders.so
/V3/usr/lib64/darktable/plugins/libcacorrect.so
/V3/usr/lib64/darktable/plugins/libcacorrectrgb.so
/V3/usr/lib64/darktable/plugins/libcensorize.so
/V3/usr/lib64/darktable/plugins/libchannelmixer.so
/V3/usr/lib64/darktable/plugins/libchannelmixerrgb.so
/V3/usr/lib64/darktable/plugins/libclahe.so
/V3/usr/lib64/darktable/plugins/libclipping.so
/V3/usr/lib64/darktable/plugins/libcolisa.so
/V3/usr/lib64/darktable/plugins/libcolorbalance.so
/V3/usr/lib64/darktable/plugins/libcolorbalancergb.so
/V3/usr/lib64/darktable/plugins/libcolorchecker.so
/V3/usr/lib64/darktable/plugins/libcolorcontrast.so
/V3/usr/lib64/darktable/plugins/libcolorcorrection.so
/V3/usr/lib64/darktable/plugins/libcolorequal.so
/V3/usr/lib64/darktable/plugins/libcolorin.so
/V3/usr/lib64/darktable/plugins/libcolorize.so
/V3/usr/lib64/darktable/plugins/libcolormapping.so
/V3/usr/lib64/darktable/plugins/libcolorout.so
/V3/usr/lib64/darktable/plugins/libcolorreconstruct.so
/V3/usr/lib64/darktable/plugins/libcolortransfer.so
/V3/usr/lib64/darktable/plugins/libcolorzones.so
/V3/usr/lib64/darktable/plugins/libcrop.so
/V3/usr/lib64/darktable/plugins/libdefringe.so
/V3/usr/lib64/darktable/plugins/libdemosaic.so
/V3/usr/lib64/darktable/plugins/libdenoiseprofile.so
/V3/usr/lib64/darktable/plugins/libdiffuse.so
/V3/usr/lib64/darktable/plugins/libdither.so
/V3/usr/lib64/darktable/plugins/libenlargecanvas.so
/V3/usr/lib64/darktable/plugins/libequalizer.so
/V3/usr/lib64/darktable/plugins/libexposure.so
/V3/usr/lib64/darktable/plugins/libfilmic.so
/V3/usr/lib64/darktable/plugins/libfilmicrgb.so
/V3/usr/lib64/darktable/plugins/libfinalscale.so
/V3/usr/lib64/darktable/plugins/libflip.so
/V3/usr/lib64/darktable/plugins/libgamma.so
/V3/usr/lib64/darktable/plugins/libglobaltonemap.so
/V3/usr/lib64/darktable/plugins/libgraduatednd.so
/V3/usr/lib64/darktable/plugins/libgrain.so
/V3/usr/lib64/darktable/plugins/libhazeremoval.so
/V3/usr/lib64/darktable/plugins/libhighlights.so
/V3/usr/lib64/darktable/plugins/libhighpass.so
/V3/usr/lib64/darktable/plugins/libhotpixels.so
/V3/usr/lib64/darktable/plugins/libinvert.so
/V3/usr/lib64/darktable/plugins/liblens.so
/V3/usr/lib64/darktable/plugins/liblevels.so
/V3/usr/lib64/darktable/plugins/libliquify.so
/V3/usr/lib64/darktable/plugins/liblowlight.so
/V3/usr/lib64/darktable/plugins/liblowpass.so
/V3/usr/lib64/darktable/plugins/liblut3d.so
/V3/usr/lib64/darktable/plugins/libmask_manager.so
/V3/usr/lib64/darktable/plugins/libmonochrome.so
/V3/usr/lib64/darktable/plugins/libnegadoctor.so
/V3/usr/lib64/darktable/plugins/libnlmeans.so
/V3/usr/lib64/darktable/plugins/liboverexposed.so
/V3/usr/lib64/darktable/plugins/liboverlay.so
/V3/usr/lib64/darktable/plugins/libprimaries.so
/V3/usr/lib64/darktable/plugins/libprofile_gamma.so
/V3/usr/lib64/darktable/plugins/librawdenoise.so
/V3/usr/lib64/darktable/plugins/librawoverexposed.so
/V3/usr/lib64/darktable/plugins/librawprepare.so
/V3/usr/lib64/darktable/plugins/librelight.so
/V3/usr/lib64/darktable/plugins/libretouch.so
/V3/usr/lib64/darktable/plugins/librgbcurve.so
/V3/usr/lib64/darktable/plugins/librgblevels.so
/V3/usr/lib64/darktable/plugins/librotatepixels.so
/V3/usr/lib64/darktable/plugins/libscalepixels.so
/V3/usr/lib64/darktable/plugins/libshadhi.so
/V3/usr/lib64/darktable/plugins/libsharpen.so
/V3/usr/lib64/darktable/plugins/libsigmoid.so
/V3/usr/lib64/darktable/plugins/libsoften.so
/V3/usr/lib64/darktable/plugins/libsplittoning.so
/V3/usr/lib64/darktable/plugins/libspots.so
/V3/usr/lib64/darktable/plugins/libtemperature.so
/V3/usr/lib64/darktable/plugins/libtonecurve.so
/V3/usr/lib64/darktable/plugins/libtoneequal.so
/V3/usr/lib64/darktable/plugins/libtonemap.so
/V3/usr/lib64/darktable/plugins/libvelvia.so
/V3/usr/lib64/darktable/plugins/libvibrance.so
/V3/usr/lib64/darktable/plugins/libvignette.so
/V3/usr/lib64/darktable/plugins/libwatermark.so
/V3/usr/lib64/darktable/plugins/libzonesystem.so
/V3/usr/lib64/darktable/plugins/lighttable/libbackgroundjobs.so
/V3/usr/lib64/darktable/plugins/lighttable/libcamera.so
/V3/usr/lib64/darktable/plugins/lighttable/libcollect.so
/V3/usr/lib64/darktable/plugins/lighttable/libcolorlabels.so
/V3/usr/lib64/darktable/plugins/lighttable/libcolorpicker.so
/V3/usr/lib64/darktable/plugins/lighttable/libcopy_history.so
/V3/usr/lib64/darktable/plugins/lighttable/libdarktable_label.so
/V3/usr/lib64/darktable/plugins/lighttable/libduplicate.so
/V3/usr/lib64/darktable/plugins/lighttable/libexport.so
/V3/usr/lib64/darktable/plugins/lighttable/libfilmstrip.so
/V3/usr/lib64/darktable/plugins/lighttable/libfilter.so
/V3/usr/lib64/darktable/plugins/lighttable/libfiltering.so
/V3/usr/lib64/darktable/plugins/lighttable/libgamepad.so
/V3/usr/lib64/darktable/plugins/lighttable/libgeotagging.so
/V3/usr/lib64/darktable/plugins/lighttable/libglobal_toolbox.so
/V3/usr/lib64/darktable/plugins/lighttable/libhinter.so
/V3/usr/lib64/darktable/plugins/lighttable/libhistogram.so
/V3/usr/lib64/darktable/plugins/lighttable/libhistory.so
/V3/usr/lib64/darktable/plugins/lighttable/libimage.so
/V3/usr/lib64/darktable/plugins/lighttable/libimage_infos.so
/V3/usr/lib64/darktable/plugins/lighttable/libimport.so
/V3/usr/lib64/darktable/plugins/lighttable/libioporder.so
/V3/usr/lib64/darktable/plugins/lighttable/liblighttable_mode.so
/V3/usr/lib64/darktable/plugins/lighttable/liblive_view.so
/V3/usr/lib64/darktable/plugins/lighttable/liblocation.so
/V3/usr/lib64/darktable/plugins/lighttable/libmap_locations.so
/V3/usr/lib64/darktable/plugins/lighttable/libmap_settings.so
/V3/usr/lib64/darktable/plugins/lighttable/libmasks.so
/V3/usr/lib64/darktable/plugins/lighttable/libmetadata.so
/V3/usr/lib64/darktable/plugins/lighttable/libmetadata_view.so
/V3/usr/lib64/darktable/plugins/lighttable/libmidi.so
/V3/usr/lib64/darktable/plugins/lighttable/libmodule_toolbox.so
/V3/usr/lib64/darktable/plugins/lighttable/libmodulegroups.so
/V3/usr/lib64/darktable/plugins/lighttable/libnavigation.so
/V3/usr/lib64/darktable/plugins/lighttable/libprint_settings.so
/V3/usr/lib64/darktable/plugins/lighttable/libratings.so
/V3/usr/lib64/darktable/plugins/lighttable/librecentcollect.so
/V3/usr/lib64/darktable/plugins/lighttable/libselect.so
/V3/usr/lib64/darktable/plugins/lighttable/libsession.so
/V3/usr/lib64/darktable/plugins/lighttable/libsnapshots.so
/V3/usr/lib64/darktable/plugins/lighttable/libstyles.so
/V3/usr/lib64/darktable/plugins/lighttable/libtagging.so
/V3/usr/lib64/darktable/plugins/lighttable/libtimeline.so
/V3/usr/lib64/darktable/plugins/lighttable/libview_toolbox.so
/V3/usr/lib64/darktable/plugins/lighttable/libviewswitcher.so
/V3/usr/lib64/darktable/views/libdarkroom.so
/V3/usr/lib64/darktable/views/liblighttable.so
/V3/usr/lib64/darktable/views/libmap.so
/V3/usr/lib64/darktable/views/libprint.so
/V3/usr/lib64/darktable/views/libslideshow.so
/V3/usr/lib64/darktable/views/libtethering.so
/usr/lib64/darktable/libdarktable.so
/usr/lib64/darktable/plugins/imageio/format/libavif.so
/usr/lib64/darktable/plugins/imageio/format/libcopy.so
/usr/lib64/darktable/plugins/imageio/format/libexr.so
/usr/lib64/darktable/plugins/imageio/format/libj2k.so
/usr/lib64/darktable/plugins/imageio/format/libjpeg.so
/usr/lib64/darktable/plugins/imageio/format/libpdf.so
/usr/lib64/darktable/plugins/imageio/format/libpfm.so
/usr/lib64/darktable/plugins/imageio/format/libpng.so
/usr/lib64/darktable/plugins/imageio/format/libppm.so
/usr/lib64/darktable/plugins/imageio/format/libtiff.so
/usr/lib64/darktable/plugins/imageio/format/libwebp.so
/usr/lib64/darktable/plugins/imageio/format/libxcf.so
/usr/lib64/darktable/plugins/imageio/storage/libdisk.so
/usr/lib64/darktable/plugins/imageio/storage/libemail.so
/usr/lib64/darktable/plugins/imageio/storage/libgallery.so
/usr/lib64/darktable/plugins/imageio/storage/liblatex.so
/usr/lib64/darktable/plugins/imageio/storage/libpiwigo.so
/usr/lib64/darktable/plugins/libashift.so
/usr/lib64/darktable/plugins/libatrous.so
/usr/lib64/darktable/plugins/libbasecurve.so
/usr/lib64/darktable/plugins/libbasicadj.so
/usr/lib64/darktable/plugins/libbilat.so
/usr/lib64/darktable/plugins/libbilateral.so
/usr/lib64/darktable/plugins/libbloom.so
/usr/lib64/darktable/plugins/libblurs.so
/usr/lib64/darktable/plugins/libborders.so
/usr/lib64/darktable/plugins/libcacorrect.so
/usr/lib64/darktable/plugins/libcacorrectrgb.so
/usr/lib64/darktable/plugins/libcensorize.so
/usr/lib64/darktable/plugins/libchannelmixer.so
/usr/lib64/darktable/plugins/libchannelmixerrgb.so
/usr/lib64/darktable/plugins/libclahe.so
/usr/lib64/darktable/plugins/libclipping.so
/usr/lib64/darktable/plugins/libcolisa.so
/usr/lib64/darktable/plugins/libcolorbalance.so
/usr/lib64/darktable/plugins/libcolorbalancergb.so
/usr/lib64/darktable/plugins/libcolorchecker.so
/usr/lib64/darktable/plugins/libcolorcontrast.so
/usr/lib64/darktable/plugins/libcolorcorrection.so
/usr/lib64/darktable/plugins/libcolorequal.so
/usr/lib64/darktable/plugins/libcolorin.so
/usr/lib64/darktable/plugins/libcolorize.so
/usr/lib64/darktable/plugins/libcolormapping.so
/usr/lib64/darktable/plugins/libcolorout.so
/usr/lib64/darktable/plugins/libcolorreconstruct.so
/usr/lib64/darktable/plugins/libcolortransfer.so
/usr/lib64/darktable/plugins/libcolorzones.so
/usr/lib64/darktable/plugins/libcrop.so
/usr/lib64/darktable/plugins/libdefringe.so
/usr/lib64/darktable/plugins/libdemosaic.so
/usr/lib64/darktable/plugins/libdenoiseprofile.so
/usr/lib64/darktable/plugins/libdiffuse.so
/usr/lib64/darktable/plugins/libdither.so
/usr/lib64/darktable/plugins/libenlargecanvas.so
/usr/lib64/darktable/plugins/libequalizer.so
/usr/lib64/darktable/plugins/libexposure.so
/usr/lib64/darktable/plugins/libfilmic.so
/usr/lib64/darktable/plugins/libfilmicrgb.so
/usr/lib64/darktable/plugins/libfinalscale.so
/usr/lib64/darktable/plugins/libflip.so
/usr/lib64/darktable/plugins/libgamma.so
/usr/lib64/darktable/plugins/libglobaltonemap.so
/usr/lib64/darktable/plugins/libgraduatednd.so
/usr/lib64/darktable/plugins/libgrain.so
/usr/lib64/darktable/plugins/libhazeremoval.so
/usr/lib64/darktable/plugins/libhighlights.so
/usr/lib64/darktable/plugins/libhighpass.so
/usr/lib64/darktable/plugins/libhotpixels.so
/usr/lib64/darktable/plugins/libinvert.so
/usr/lib64/darktable/plugins/liblens.so
/usr/lib64/darktable/plugins/liblevels.so
/usr/lib64/darktable/plugins/libliquify.so
/usr/lib64/darktable/plugins/liblowlight.so
/usr/lib64/darktable/plugins/liblowpass.so
/usr/lib64/darktable/plugins/liblut3d.so
/usr/lib64/darktable/plugins/libmask_manager.so
/usr/lib64/darktable/plugins/libmonochrome.so
/usr/lib64/darktable/plugins/libnegadoctor.so
/usr/lib64/darktable/plugins/libnlmeans.so
/usr/lib64/darktable/plugins/liboverexposed.so
/usr/lib64/darktable/plugins/liboverlay.so
/usr/lib64/darktable/plugins/libprimaries.so
/usr/lib64/darktable/plugins/libprofile_gamma.so
/usr/lib64/darktable/plugins/librawdenoise.so
/usr/lib64/darktable/plugins/librawoverexposed.so
/usr/lib64/darktable/plugins/librawprepare.so
/usr/lib64/darktable/plugins/librelight.so
/usr/lib64/darktable/plugins/libretouch.so
/usr/lib64/darktable/plugins/librgbcurve.so
/usr/lib64/darktable/plugins/librgblevels.so
/usr/lib64/darktable/plugins/librotatepixels.so
/usr/lib64/darktable/plugins/libscalepixels.so
/usr/lib64/darktable/plugins/libshadhi.so
/usr/lib64/darktable/plugins/libsharpen.so
/usr/lib64/darktable/plugins/libsigmoid.so
/usr/lib64/darktable/plugins/libsoften.so
/usr/lib64/darktable/plugins/libsplittoning.so
/usr/lib64/darktable/plugins/libspots.so
/usr/lib64/darktable/plugins/libtemperature.so
/usr/lib64/darktable/plugins/libtonecurve.so
/usr/lib64/darktable/plugins/libtoneequal.so
/usr/lib64/darktable/plugins/libtonemap.so
/usr/lib64/darktable/plugins/libvelvia.so
/usr/lib64/darktable/plugins/libvibrance.so
/usr/lib64/darktable/plugins/libvignette.so
/usr/lib64/darktable/plugins/libwatermark.so
/usr/lib64/darktable/plugins/libzonesystem.so
/usr/lib64/darktable/plugins/lighttable/libbackgroundjobs.so
/usr/lib64/darktable/plugins/lighttable/libcamera.so
/usr/lib64/darktable/plugins/lighttable/libcollect.so
/usr/lib64/darktable/plugins/lighttable/libcolorlabels.so
/usr/lib64/darktable/plugins/lighttable/libcolorpicker.so
/usr/lib64/darktable/plugins/lighttable/libcopy_history.so
/usr/lib64/darktable/plugins/lighttable/libdarktable_label.so
/usr/lib64/darktable/plugins/lighttable/libduplicate.so
/usr/lib64/darktable/plugins/lighttable/libexport.so
/usr/lib64/darktable/plugins/lighttable/libfilmstrip.so
/usr/lib64/darktable/plugins/lighttable/libfilter.so
/usr/lib64/darktable/plugins/lighttable/libfiltering.so
/usr/lib64/darktable/plugins/lighttable/libgamepad.so
/usr/lib64/darktable/plugins/lighttable/libgeotagging.so
/usr/lib64/darktable/plugins/lighttable/libglobal_toolbox.so
/usr/lib64/darktable/plugins/lighttable/libhinter.so
/usr/lib64/darktable/plugins/lighttable/libhistogram.so
/usr/lib64/darktable/plugins/lighttable/libhistory.so
/usr/lib64/darktable/plugins/lighttable/libimage.so
/usr/lib64/darktable/plugins/lighttable/libimage_infos.so
/usr/lib64/darktable/plugins/lighttable/libimport.so
/usr/lib64/darktable/plugins/lighttable/libioporder.so
/usr/lib64/darktable/plugins/lighttable/liblighttable_mode.so
/usr/lib64/darktable/plugins/lighttable/liblive_view.so
/usr/lib64/darktable/plugins/lighttable/liblocation.so
/usr/lib64/darktable/plugins/lighttable/libmap_locations.so
/usr/lib64/darktable/plugins/lighttable/libmap_settings.so
/usr/lib64/darktable/plugins/lighttable/libmasks.so
/usr/lib64/darktable/plugins/lighttable/libmetadata.so
/usr/lib64/darktable/plugins/lighttable/libmetadata_view.so
/usr/lib64/darktable/plugins/lighttable/libmidi.so
/usr/lib64/darktable/plugins/lighttable/libmodule_toolbox.so
/usr/lib64/darktable/plugins/lighttable/libmodulegroups.so
/usr/lib64/darktable/plugins/lighttable/libnavigation.so
/usr/lib64/darktable/plugins/lighttable/libprint_settings.so
/usr/lib64/darktable/plugins/lighttable/libratings.so
/usr/lib64/darktable/plugins/lighttable/librecentcollect.so
/usr/lib64/darktable/plugins/lighttable/libselect.so
/usr/lib64/darktable/plugins/lighttable/libsession.so
/usr/lib64/darktable/plugins/lighttable/libsnapshots.so
/usr/lib64/darktable/plugins/lighttable/libstyles.so
/usr/lib64/darktable/plugins/lighttable/libtagging.so
/usr/lib64/darktable/plugins/lighttable/libtimeline.so
/usr/lib64/darktable/plugins/lighttable/libview_toolbox.so
/usr/lib64/darktable/plugins/lighttable/libviewswitcher.so
/usr/lib64/darktable/views/libdarkroom.so
/usr/lib64/darktable/views/liblighttable.so
/usr/lib64/darktable/views/libmap.so
/usr/lib64/darktable/views/libprint.so
/usr/lib64/darktable/views/libslideshow.so
/usr/lib64/darktable/views/libtethering.so
/usr/lib64/libdarktable.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/darktable/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/darktable/3704f4680301a60004b20f94e0b5b8c7ff1484a9
/usr/share/package-licenses/darktable/39a21f33cadea18adcc23bf808d7d5ea6419c8b1
/usr/share/package-licenses/darktable/6baddc7988322d021a187ff7d1d0fb9e2a784e20
/usr/share/package-licenses/darktable/75e5bae837deb898dae4cb65c4890b1ab825c6b6
/usr/share/package-licenses/darktable/8624bcdae55baeef00cd11d5dfcfa60f68710a02
/usr/share/package-licenses/darktable/c24b9c7ef03687bf0141f85a1b7ed81459944c3c
/usr/share/package-licenses/darktable/c996ffd4c579d586b7d86e158af6042018c3c422
/usr/share/package-licenses/darktable/d9f41c058914394e203adb253057643e047576a3
/usr/share/package-licenses/darktable/fc356b2c50a063b663cc14dde29bc0ab9e7bec51
/usr/share/package-licenses/darktable/ff3ed70db4739b3c6747c7f624fe2bad70802987

%files man
%defattr(0644,root,root,0755)
/usr/share/man/de/man1/darktable-cli.1
/usr/share/man/de/man1/darktable-cltest.1
/usr/share/man/de/man1/darktable-cmstest.1
/usr/share/man/de/man1/darktable-generate-cache.1
/usr/share/man/de/man1/darktable.1
/usr/share/man/es/man1/darktable-cli.1
/usr/share/man/es/man1/darktable-cltest.1
/usr/share/man/es/man1/darktable-cmstest.1
/usr/share/man/es/man1/darktable-generate-cache.1
/usr/share/man/es/man1/darktable.1
/usr/share/man/fr/man1/darktable-cli.1
/usr/share/man/fr/man1/darktable-cltest.1
/usr/share/man/fr/man1/darktable-cmstest.1
/usr/share/man/fr/man1/darktable-generate-cache.1
/usr/share/man/fr/man1/darktable.1
/usr/share/man/man1/darktable-cli.1
/usr/share/man/man1/darktable-cltest.1
/usr/share/man/man1/darktable-cmstest.1
/usr/share/man/man1/darktable-generate-cache.1
/usr/share/man/man1/darktable.1

%files locales -f darktable.lang
%defattr(-,root,root,-)

